### ISSUE TITLE
Unknown option: debug & structure_detection

### ISSUE THREAD

**Issue by edxmorgan** [jgillis/fatrop_demo#2]
python3 after.py       
Traceback (most recent call last):
  File "/Users/dev_ws/src/fatrop_demo/after.py", line 119, in <module>
    sol = opti.solve()
          ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/casadi/casadi.py", line 47938, in solve
    return _casadi.Opti_solve(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:157:
.../casadi/core/options.cpp:244: Unknown option: debug

Did you mean one of the following?
> "dump"          [OT_BOOL]      "Dump function to file upon first evaluation. [false]"
> "ng"          [OT_INTVECTOR]      "Number of non-dynamic constraints, length N+1"
> "nu"          [OT_INTVECTOR]      "Number of controls, length N"
> "cache"          [OT_DICT]      "Prepopulate the function cache. Default: empty"
> "calc_g"          [OT_BOOL]      "Calculate 'g' in the Nlpsol base class"
Use print_options() to get a full list of options.

  File "/Users/dev_ws/src/fatrop_demo/after.py", line 119, in <module>
    sol = opti.solve()
          ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/casadi/casadi.py", line 47938, in solve
    return _casadi.Opti_solve(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:157:
.../casadi/core/options.cpp:244: Unknown option: structure_detection

Did you mean one of the following?
> "oracle_options"          [OT_DICT]      "Options to be passed to the oracle function"
> "forward_options"          [OT_DICT]      "Options to be passed to a forward mode constructor"
> "record_time"          [OT_BOOL]      "record information about execution time, for retrieval with stats()."
> "reverse_options"          [OT_DICT]      "Options to be passed to a reverse mode constructor"
> "specific_options"          [OT_DICT]      "Options for specific auto-generated functions, overwriting the defaults from common_options. Nested dictionary."
Use print_options() to get a full list of options.

**Comment by edxmorgan** [comment]
installation was done using this wheel

casadi-3.6.5.dev+fatrop.nlp-cp311-none-macosx_11_0_arm64.whl
